# Generated by Django 4.1.7 on 2023-05-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealESRGANAPP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
