# Generated by Django 4.1.7 on 2023-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imhanceuser',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
